(function (LOG_LEVEL_INDEX) {
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["EMERGENCY"] = 0] = "EMERGENCY";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["ALERT"] = 1] = "ALERT";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["CRITICAL"] = 2] = "CRITICAL";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["ERROR"] = 3] = "ERROR";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["WARNING"] = 4] = "WARNING";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["NOTICE"] = 5] = "NOTICE";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["INFO"] = 6] = "INFO";
    LOG_LEVEL_INDEX[LOG_LEVEL_INDEX["DEBUG"] = 7] = "DEBUG";
})(exports.LOG_LEVEL_INDEX || (exports.LOG_LEVEL_INDEX = {}));
var LOG_LEVEL_INDEX = exports.LOG_LEVEL_INDEX;
(function (LOG_LEVELS) {
    LOG_LEVELS[LOG_LEVELS['EMERGENCY'] = 0] = 'EMERGENCY';
    LOG_LEVELS[LOG_LEVELS['ALERT'] = 1] = 'ALERT';
    LOG_LEVELS[LOG_LEVELS['CRITICAL'] = 2] = 'CRITICAL';
    LOG_LEVELS[LOG_LEVELS['ERROR'] = 3] = 'ERROR';
    LOG_LEVELS[LOG_LEVELS['WARNING'] = 4] = 'WARNING';
    LOG_LEVELS[LOG_LEVELS['NOTICE'] = 5] = 'NOTICE';
    LOG_LEVELS[LOG_LEVELS['INFO'] = 6] = 'INFO';
    LOG_LEVELS[LOG_LEVELS['DEBUG'] = 7] = 'DEBUG';
})(exports.LOG_LEVELS || (exports.LOG_LEVELS = {}));
var LOG_LEVELS = exports.LOG_LEVELS;
